### ISSUE TITLE
Non-cancelable event

### ISSUE THREAD

**Issue by rowanc1** [d3/d3-drag#70] opened 2020-04-29 01:09 UTC
I am getting errors in the `noevent.js` file saying:

`Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`

The advice I have seen around the internet is to add a:

```javascript
export default function() {
  if (event.cancelable) event.preventDefault();
  event.stopImmediatePropagation();
}
```

![image](https://user-images.githubusercontent.com/913249/80552152-f0fba980-8982-11ea-9c92-ca6317e14d1a.png)

Let me know if you want me to open a PR!

---
Version: 1.2.5
Using: Chrome 81.0.4044.122 (in emulator)
Platform: Mac

**Comment by Fil** [comment] 2020-07-24 12:54
This seems similar to https://github.com/d3/d3-zoom/issues/195 and https://github.com/d3/d3-zoom/issues/175 ; it would be nice to be able to reproduce the issue with a given webpage and browser.

**Comment by AVatch** [comment] 2020-11-03 04:28
This happens to me as well in an Ionic (https://ionicframework.com/) project with the touch inputs turned on in Chrome.

I suspect it may be related to the ion-content since it has it's own scroll logic.

**Comment by mbostock** [comment] 2021-06-09 15:59
I believe this was because the event listeners were not declared non-passive, which was the historical default, but broken in recent browsers. Hence, this is a duplicate of #78 which is now fixed.

**Closed by mbostock** 2021-06-09 15:59 UTC
